Ultimando el cd

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -17,7 +17,7 @@ jobs:
 
       # Instalar dependencias
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: pip install -r requirements.txt 
 
       # Ejecutar pruebas
       - name: Run tests
@@ -45,3 +45,38 @@ jobs:
           context: .
           push: true
           tags: sebaskrieg/edteam-fastapi-demo:latest
+
+#Comenzar con la implementación de la acción de CI/CD
+  cd:
+    runs-on: ubuntu-latest
+    needs: ci
+    steps:
+
+      - name: Conectarse de forma remota al servidor
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.SSH_KEY }}
+          script: |
+            echo "Conexión exitosa"
+            sleep 5
+            API=$(docker ps -q -f name=edteam-fastapi-demo)
+            if [ ! -z "$API" ]; then
+              docker stop $API
+              docker rm $API
+            fi
+            echo "Descargando imagen"
+            docker pull sebaskrieg/edteam-fastapi-demo:latest
+            docker run -d -p 80:8080 --name edteam-fastapi-demo sebaskrieg/edteam-fastapi-demo:latest    
+      - name: Verificar conexión
+        env:
+          ENDPOINT: ${{ secrets.ENDPOINT }}
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT)
+          if [ $RESPONSE -eq 200 ]; then
+            echo "Conexión exitosa"
+          else
+            echo "Error en la conexión"
+            exit 1
+          fi
